### ISSUE TITLE
Build Game Prototype

### ISSUE THREAD

**Issue by JulianMH** [JulianMH/Innerspace-Coding-Challenge#2]
## Task description

Build a "quick and dirty" prototype of the game that has the following features:
- [x] level generation
- [x] player collision and movement
- [x] game over and level reset
- [x] score counting and difficulty progression
- [x] highscore tracking and persistence

### Time estimation

3 hours

## Notes

**Comment by JulianMH** [comment]
Task took 2 hours.
