### ISSUE TITLE
Menu System

### ISSUE THREAD

**Issue by JulianMH** [JulianMH/Innerspace-Coding-Challenge#4]
## Task description

Build the menu system:
- [x] game over screen (with support for resetting game)
- [x] game paused screen (with support for pausing gameplay)
- [x] main menu screen
- [x] new high score information

### Time estimation

2 hours

## Notes

**Comment by JulianMH** [comment]
Task took 2 hours.
